"""empty message

Revision ID: b38ddd59cb62
Revises: f034026f5c09
Create Date: 2024-03-25 10:39:33.202446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b38ddd59cb62'
down_revision = 'f034026f5c09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('explanation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('class_session_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_explanation_class_session_id', 'class_session', ['class_session_id'], ['id'])

    with op.batch_alter_table('reason', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('class_session_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_reason_class_session_id', 'class_session', ['class_session_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reason', schema=None) as batch_op:
        batch_op.drop_constraint('fk_reason_class_session_id', type_='foreignkey')
        batch_op.drop_column('class_session_id')
        batch_op.drop_column('timestamp')

    with op.batch_alter_table('explanation', schema=None) as batch_op:
        batch_op.drop_constraint('fk_explanation_class_session_id', type_='foreignkey')
        batch_op.drop_column('class_session_id')

    # ### end Alembic commands ###
