"""empty message

Revision ID: f034026f5c09
Revises: 
Create Date: 2024-03-12 12:36:51.317712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f034026f5c09'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mood', schema=None) as batch_op:
        batch_op.add_column(sa.Column('class_session_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_mood_class_session_id', 'class_session', ['class_session_id'], ['id'])

    # ### end Alembic commands ###



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mood', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('class_session_id')

    # ### end Alembic commands ###
