"""empty message

Revision ID: f408d7f0722c
Revises: b38ddd59cb62
Create Date: 2024-03-25 11:18:57.313475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f408d7f0722c'
down_revision = 'b38ddd59cb62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('explanation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mood_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_explanation_class_session_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_explanation_mood_id', 'mood', ['mood_id'], ['id'])

        batch_op.drop_column('class_session_id')

    with op.batch_alter_table('reason', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mood_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_reason_class_session_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_reason_mood_id', 'mood', ['mood_id'], ['id'])

        batch_op.drop_column('class_session_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reason', schema=None) as batch_op:
        batch_op.add_column(sa.Column('class_session_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_reason_class_session_id', 'class_session', ['class_session_id'], ['id'])
        batch_op.drop_column('mood_id')

    with op.batch_alter_table('explanation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('class_session_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_explanation_class_session_id', 'class_session', ['class_session_id'], ['id'])
        batch_op.drop_column('mood_id')

    # ### end Alembic commands ###
